export const SEARCH_TRENDS_REQUEST = 'SEARCH_TRENDS_REQUEST';
export const SEARCH_TRENDS_SUCCESS = 'SEARCH_TRENDS_SUCCESS';
export const SEARCH_TRENDS_FAIL = 'SEARCH_TRENDS_FAIL';

export const FILTER_TRENDS_REQUEST = 'FILTER_TRENDS_REQUEST';
export const FILTER_TRENDS_SUCCESS = 'FILTER_TRENDS_SUCCESS';
export const FILTER_TRENDS_FAIL = 'FILTER_TRENDS_FAIL';
export const GET_TREND_REQUEST = 'GET_TREND_REQUEST';
export const GET_TREND_SUCCESS = 'GET_TREND_SUCCESS';
export const GET_TREND_FAIL = 'GET_TREND_FAIL';
export const SET_TREND_FILTERS = 'SET_TREND_FILTERS';
export const CLEAR_TREND_FILTERS = 'CLEAR_TREND_FILTERS';
export const SET_TREND_SEARCH = 'SET_TREND_SEARCH';
export const SET_TREND_CATEGORY = 'SET_TREND_CATEGORY';
export const SET_TREND_SEASON = 'SET_TREND_SEASON';
export const FETCH_TRENDS_REQUEST = 'FETCH_TRENDS_REQUEST';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAIL = 'FETCH_TRENDS_FAIL';
export const SET_TREND_PAGE = 'SET_TREND_PAGE';
export const SET_TREND_LIMIT = 'SET_TREND_LIMIT';
export const SET_TREND_SORT = 'SET_TREND_SORT';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const FETCH_TRENDS_SERVER_UNREACHABLE = 'FETCH_TRENDS_SERVER_UNREACHABLE';

// Share trend action types
export const SHARE_TREND_REQUEST = 'SHARE_TREND_REQUEST';
export const SHARE_TREND_SUCCESS = 'SHARE_TREND_SUCCESS';
export const SHARE_TREND_FAIL = 'SHARE_TREND_FAIL';

// Trend Types
export const CREATE_TREND = 'CREATE_TREND';
export const GET_TRENDS = 'GET_TRENDS';
export const GET_TREND = 'GET_TREND';
export const UPDATE_TREND = 'UPDATE_TREND';
export const DELETE_TREND = 'DELETE_TREND';
export const TREND_ERROR = 'TREND_ERROR';
export const CLEAR_TREND = 'CLEAR_TREND';

// redux/types.js
export const FETCH_WORKSPACE_REQUEST = 'FETCH_WORKSPACE_REQUEST';
export const FETCH_WORKSPACE_SUCCESS = 'FETCH_WORKSPACE_SUCCESS';
export const FETCH_WORKSPACE_FAIL = 'FETCH_WORKSPACE_FAIL';

export const CREATE_TREND_REQUEST = 'CREATE_TREND_REQUEST';
export const CREATE_TREND_SUCCESS = 'CREATE_TREND_SUCCESS';
export const CREATE_TREND_FAIL = 'CREATE_TREND_FAIL';